Break sentences over 512 tokens into smaller chunks
RENCI-NER/nemo-serve pull request #36
Opened 2024-04-11 16:32 UTC by mbacon-renci

This addresses DUG-459 (https://renci.atlassian.net/browse/DUG-459) where input text that tokenizes to sentences longer than 512 tokens overloads the model.

To fix this, if a sentence is over `window_size` tokens (usually 512), it is first split by semi-colon, and if that still results in oversized sentences, it is split again by tokens and then broken into roughly equal sized chunks that will fit inside the window. 

A caveat with this: at present this final split first breaks the segment into tokens using `text_to_tokens,` and then re-assembles it in chunks of an appropriate size using `tokens_to_text.` This may add or remove spaces as the processes of splitting and then re-joining tokens are not perfect inverses of each other.

2024-04-11 16:40 UTC, mbacon-renci commented
A rough version of this code is in testing here: https://nemo-jupyter.apps.renci.org/notebooks/notebooks/test_sliding_window_with_stack.ipynb

2024-04-16 13:43 UTC, YaphetKG commented
Hi Michael thanks this all works well but one slight issue is i think once the annotations are done when i re-constructs the final object to return it does return spans like 
```
{
      "id": "I17-26",
      "span": {
        "begin": 7625,
        "end": 7633
      },
      "obj": "biolink:Cohort",
      "text": "children"
    },
```

And i believe some of the spans are a little offset 
![image](https://github.com/RENCI-NER/nemo-serve/assets/45075777/dc2ff1ce-4709-4e37-8578-adec8ad13a62)

tool used to verify (https://textae.pubannotation.org/editor.html?mode=edit)

2024-04-16 13:43 UTC, YaphetKG requested changes
view PR comment

2024-04-19 20:52 UTC, mbacon-renci commented
I believe the latest commit addresses these problems.

2024-05-01 17:40 UTC, mbacon-renci commented
Most recent update should at least fix any problems with whitespace disappearance or token orphaning. (Which looks like ## appearing at the beginning of word fragments). Hopefully this actually gets us over the line.

2024-05-06 20:12 UTC, YaphetKG approved these changes

2024-05-06 20:12 UTC, merged